### ISSUE TITLE
Emit a warning if the base URL leads to an empty page

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#953]
We met with a potential user today who initially configured their ADO pipeline with a `url` parameter that was slightly off, resulting in the scanner seeing a blank page. The scan appeared successful, but wasn't really scanning anything meaningful.

It would be nice for the action to detect this case and warn about the probable misconfiguration. Maybe something along the lines of "empty body" and/or "4xx/5xx response code" to trigger a warning. It should probably either only apply to the base URL, be suppressable, or both.

**Comment by asksep** [comment]
PM to determine next steps for UI changes

**Comment by asksep** [comment]
We will bundle this into feature work: ADO-Improvements -1

**Comment by brocktaylor7** [comment]
I'm not certain we want to pursue this.  If the webserver returns a success code the page is scanned. The scanner package does check the status codes and throws if the page doesn't exist. In the case of the user mentioned above, I assume the webserver was serving a page it just happened to be empty? That seems like an edge case that on its own is probably good for the end-user to fix.

The accessibility-insights-scan package doesn't currently have infrastructure for detecting a blank page.  If the base URL or a linked page is served successfully with a 200 status code but is blank it will return two failure instances from axe-core: 

```
2 failure instances
* (1) document-title:  Ensures each HTML document contains a non-empty <title> element
* (1) html-has-lang:  Ensures every HTML document has a lang attribute
```

There is also no way of doing this without modifying the service repo to handle this case.  If we were to pursue this further, we would likely want to make it optional with a flag that can be passed into the crawler. We would also have to figure out how to structure the output properly to handle this scenario, as the crawler is expected to return axe results. 

This is the last open issue on the ADO-improvements-1 feature. I talked to Rob and he said he was okay with either closing this issue as-is if everyone agrees. Otherwise the plan will be to push it to a later feature.

**Comment by ThanyaLeif** [comment]
Closed after discussion with the managers.
